```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
```

```{r}
df <- data.frame(
  prob_assigned = c(2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 77.5, 82.5, 87.5, 92.5, 97.5),
  percent_resolved_pos = c(2.5, 5.7, 10.2, 14.1, 18.5, 24.5, 29.4, 33.2, 39.7, 49.3, 51.8, 57.2, 58.3, 64.7, 70.1, 73.4, 79.2, 85.9, 90.7, 96.0),
  num_markets = c(2667, 3167, 2858, 2833, 2570, 2398, 2517, 2553, 3093, 5080, 3681, 3383, 2602, 2626, 2377, 2330, 2133, 2074, 1910, 1798)
)

# Divide prob_assigned and percent_resolved_pos by 100
df$prob_assigned <- df$prob_assigned / 100
df$percent_resolved_pos <- df$percent_resolved_pos / 100
```

```{r}
exp_frac_aligned <- function(N = 383, p_gov = 0.85, lessthan = 0.79, mw = 4096) {
  fracaligned <- numeric(mw)
  for (i in 1:mw) {
    outcomes <- runif(N) < p_gov
    fracaligned[i] <- sum(outcomes) / N
  }
  res <- sum(fracaligned < lessthan) / mw

  # Plotting
  hist(fracaligned,
    breaks = 100, main = paste("Instant Reliability Significance\nN=", N, ", p_gov=", p_gov, ", mw=", mw),
    xlab = "Fraction Aligned", ylab = "Density", xlim = c(0, 1), col = "lightblue", freq = FALSE
  )
  abline(v = lessthan, col = "red")
  legend("topright", legend = paste("P(fracaligned <", lessthan, ") =", format(res, digits = 3, scientific = FALSE)), col = "black", lty = 1)

  return(res)
}

interval <- function(N, p_gov, mw = 4096) {
  fracaligned <- numeric(mw)
  for (i in 1:mw) {
    outcomes <- runif(N) < p_gov
    fracaligned[i] <- sum(outcomes) / N
  }
  # return the 2.5th and 97.5th percentiles
  return(quantile(fracaligned, c(0.025, 0.975)))
}
```

```{r}
# Add exp_frac_aligned to the df - N = num_markets, p_gov = prob_assigned, lessthan = percent_resolved_pos
df$exp_frac_aligned <- mapply(exp_frac_aligned, N = df$num_markets, p_gov = df$prob_assigned, lessthan = df$percent_resolved_pos)

# Add interval to the df - N = num_markets, p_gov = prob_assigned
df <- df %>%
  rowwise() %>%
  mutate(
    interval_values = list(interval(num_markets, prob_assigned)),
    interval_lower = interval_values[1],
    interval_upper = interval_values[2]
  ) %>%
  ungroup() %>%
  select(-interval_values)
```

```{r}
ggplot(df, aes(x = prob_assigned, y = percent_resolved_pos)) +
  geom_point(size = 3, alpha = 0.6) +
  geom_ribbon(aes(ymin = interval_lower, ymax = interval_upper), alpha = 0.2, fill = "blue") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "darkgreen") +
  labs(x = "Prob Assigned", y = "Percent Resolved Pos", title = "Manifold Reliability") +
  theme_clean()

ggsave("manifold-calibration.png", width = 6, height = 6, dpi = 300)
```